fixing incorrect use of limit
autocompletejs/autocomplete.js pull request #32
Opened 2016-11-12 17:59 UTC by iamkhush

Here were are not using the `Limit` parameter to limit the results loaded.
I think this is an appropriate fix

2016-11-21 02:54 UTC, iamkhush commented
Is the pull request clear about its purpose?

2016-11-23 11:43 UTC, baptistedonaux commented
Hi and sorry my "brain-latency" :-p 

Thank you for your fix ! I have just suggest you a little modification.

2016-11-26 20:50 UTC, iamkhush commented
Hey, looks like its alright now.

2016-11-28 08:28 UTC, baptistedonaux requested changes

2016-11-28 08:28 UTC, baptistedonaux commented on src/autocomplete.ts
> +            var limit = this._Limit();
Could you typed your parameter (```: number```) and merge this variable with previous.

2016-11-28 08:29 UTC, baptistedonaux commented on src/autocomplete.ts
> +            var limit = this._Limit();
Sorry, I had missing to send my request changes.

2016-11-28 10:16 UTC, iamkhush commented on src/autocomplete.ts
> +            var limit = this._Limit();
Do you mean `var limit = Number(this._Limit())` ?

2016-12-07 08:13 UTC, baptistedonaux commented on src/autocomplete.ts
> +            var limit = this._Limit();
Fixed into https://github.com/autocompletejs/autocomplete.js/pull/32/commits/3cf6bcfc90600112298044400177ec19015d89c3

2016-12-07 08:14 UTC, baptistedonaux approved these changes

2016-12-07 08:15 UTC, merged

2016-12-07 08:19 UTC, baptistedonaux commented
```v2.1.4``` just released ! Thanks for your fixes !